# docker - Classical Format (All Rules)
# Includes all rule types
# Rules are optimized and sorted for best performance
payload:

  # DOMAIN (3 rules)
  - 'DOMAIN,d1q6f0aelx0por.cloudfront.net'
  - 'DOMAIN,d2wy8f7a9ursnm.cloudfront.net'
  - 'DOMAIN,d36jcksde1wxzq.cloudfront.net'

  # DOMAIN-SUFFIX (4 rules)
  - 'DOMAIN-SUFFIX,docker.io'
  - 'DOMAIN-SUFFIX,docker.com'
  - 'DOMAIN-SUFFIX,dockerhub.com'
  - 'DOMAIN-SUFFIX,compose-spec.io'
